#!/bin/sh
echo -e "\033[1;36m Cleaning moment js files ... \033[0m\n"

rm -rf ./node_modules/moment/locale/ar.js
rm -rf ./node_modules/moment/locale/ar-dz.js
rm -rf ./node_modules/moment/locale/ar-kw.js
rm -rf ./node_modules/moment/locale/ar-ly.js
rm -rf ./node_modules/moment/locale/ar-ma.js
rm -rf ./node_modules/moment/locale/ar-sa.js
rm -rf ./node_modules/moment/locale/ar-tn.js
rm -rf ./node_modules/moment/locale/az.js
rm -rf ./node_modules/moment/locale/be.js
rm -rf ./node_modules/moment/locale/bg.js
rm -rf ./node_modules/moment/locale/bm.js
rm -rf ./node_modules/moment/locale/bn.js
rm -rf ./node_modules/moment/locale/bo.js
rm -rf ./node_modules/moment/locale/br.js
rm -rf ./node_modules/moment/locale/bs.js
rm -rf ./node_modules/moment/locale/ca.js
rm -rf ./node_modules/moment/locale/cs.js
rm -rf ./node_modules/moment/locale/cv.js
rm -rf ./node_modules/moment/locale/cy.js
rm -rf ./node_modules/moment/locale/da.js
rm -rf ./node_modules/moment/locale/de.js
rm -rf ./node_modules/moment/locale/de-at.js
rm -rf ./node_modules/moment/locale/de-ch.js
rm -rf ./node_modules/moment/locale/dv.js
rm -rf ./node_modules/moment/locale/el.js
rm -rf ./node_modules/moment/locale/en-au.js
rm -rf ./node_modules/moment/locale/en-ca.js
rm -rf ./node_modules/moment/locale/en-ie.js
rm -rf ./node_modules/moment/locale/en-nz.js
rm -rf ./node_modules/moment/locale/eo.js
rm -rf ./node_modules/moment/locale/es.js
rm -rf ./node_modules/moment/locale/es-do.js
rm -rf ./node_modules/moment/locale/es-us.js
rm -rf ./node_modules/moment/locale/et.js
rm -rf ./node_modules/moment/locale/eu.js
rm -rf ./node_modules/moment/locale/eu.js
rm -rf ./node_modules/moment/locale/fa.js
rm -rf ./node_modules/moment/locale/fi.js
rm -rf ./node_modules/moment/locale/fo.js
rm -rf ./node_modules/moment/locale/fr.js
rm -rf ./node_modules/moment/locale/fr-ca.js
rm -rf ./node_modules/moment/locale/fr-ch.js
rm -rf ./node_modules/moment/locale/fy.js
rm -rf ./node_modules/moment/locale/gd.js
rm -rf ./node_modules/moment/locale/gl.js
rm -rf ./node_modules/moment/locale/gom-latn.js
rm -rf ./node_modules/moment/locale/gu.js
rm -rf ./node_modules/moment/locale/he.js
rm -rf ./node_modules/moment/locale/hi.js
rm -rf ./node_modules/moment/locale/hr.js
rm -rf ./node_modules/moment/locale/hu.js
rm -rf ./node_modules/moment/locale/hy-am.js
rm -rf ./node_modules/moment/locale/id.js
rm -rf ./node_modules/moment/locale/is.js
rm -rf ./node_modules/moment/locale/it.js
rm -rf ./node_modules/moment/locale/jv.js
rm -rf ./node_modules/moment/locale/ka.js
rm -rf ./node_modules/moment/locale/kk.js
rm -rf ./node_modules/moment/locale/km.js
rm -rf ./node_modules/moment/locale/kn.js
rm -rf ./node_modules/moment/locale/ko.js
rm -rf ./node_modules/moment/locale/ky.js
rm -rf ./node_modules/moment/locale/lb.js
rm -rf ./node_modules/moment/locale/lo.js
rm -rf ./node_modules/moment/locale/lt.js
rm -rf ./node_modules/moment/locale/lv.js
rm -rf ./node_modules/moment/locale/me.js
rm -rf ./node_modules/moment/locale/mi.js
rm -rf ./node_modules/moment/locale/mk.js
rm -rf ./node_modules/moment/locale/ml.js
rm -rf ./node_modules/moment/locale/mr.js
rm -rf ./node_modules/moment/locale/ms.js
rm -rf ./node_modules/moment/locale/ms-my.js
rm -rf ./node_modules/moment/locale/mt.js
rm -rf ./node_modules/moment/locale/my.js
rm -rf ./node_modules/moment/locale/nb.js
rm -rf ./node_modules/moment/locale/ne.js
rm -rf ./node_modules/moment/locale/nl.js
rm -rf ./node_modules/moment/locale/nl-be.js
rm -rf ./node_modules/moment/locale/nn.js
rm -rf ./node_modules/moment/locale/pa-in.js
rm -rf ./node_modules/moment/locale/pl.js
rm -rf ./node_modules/moment/locale/pt-br.js
rm -rf ./node_modules/moment/locale/ro.js
rm -rf ./node_modules/moment/locale/ru.js
rm -rf ./node_modules/moment/locale/sd.js
rm -rf ./node_modules/moment/locale/se.js
rm -rf ./node_modules/moment/locale/si.js
rm -rf ./node_modules/moment/locale/sk.js
rm -rf ./node_modules/moment/locale/sl.js
rm -rf ./node_modules/moment/locale/sq.js
rm -rf ./node_modules/moment/locale/sr.js
rm -rf ./node_modules/moment/locale/sr-cyrl.js
rm -rf ./node_modules/moment/locale/ss.js
rm -rf ./node_modules/moment/locale/sv.js
rm -rf ./node_modules/moment/locale/sw.js
rm -rf ./node_modules/moment/locale/ta.js
rm -rf ./node_modules/moment/locale/te.js
rm -rf ./node_modules/moment/locale/tet.js
rm -rf ./node_modules/moment/locale/th.js
rm -rf ./node_modules/moment/locale/tl-ph.js
rm -rf ./node_modules/moment/locale/tlh.js
rm -rf ./node_modules/moment/locale/tr.js
rm -rf ./node_modules/moment/locale/tzl.js
rm -rf ./node_modules/moment/locale/tzm.js
rm -rf ./node_modules/moment/locale/tzm-latn.js
rm -rf ./node_modules/moment/locale/uk.js
rm -rf ./node_modules/moment/locale/ur.js
rm -rf ./node_modules/moment/locale/uz.js
rm -rf ./node_modules/moment/locale/uz-latn.js
rm -rf ./node_modules/moment/locale/vi.js
rm -rf ./node_modules/moment/locale/x-pseudo.js
rm -rf ./node_modules/moment/locale/yo.js
rm -rf ./node_modules/moment/locale/yo.js
rm -rf ./node_modules/moment/locale/zh-hk.js
rm -rf ./node_modules/moment/locale/zh-tw.js
mv ./node_modules/moment/locale/zh-cn.js ./node_modules/moment/locale/zh.js > /dev/null 2>&1 &
