export enum SectionExqEnum {
  MTP = 'M',
  STAFF_ON_DEMAND = 'S',
  COMMUNITY_CROUD = 'C',
  ALGORITHMS_DATA = 'A',
  LEVERAGED_ASSETS = 'L',
  ENGAGEMENT = 'E',
  INTERFACES = 'I',
  DASHBOARDS = 'D',
  EXPERIMENTATION = 'X',
  AUTONOMY = 'F',
  SOCIAL = 'O',
  BUSINESS_MODEL = 'B'
}

export enum NameExqEnum {
  M = 'MTP',
  S = 'STAFF_ON_DEMAND',
  C = 'COMMUNITY_CROUD',
  A = 'ALGORITHMS_DATA',
  L = 'LEVERAGED_ASSETS',
  E = 'ENGAGEMENT',
  I = 'INTERFACES',
  D = 'DASHBOARDS',
  X = 'EXPERIMENTATION',
  F = 'AUTONOMY',
  O = 'SOCIAL',
  B = 'BUSINESS_MODEL',
}
